# ------------------------------------------------------------------
#yaml-language-server: $schema=values.schema.json
# title               : Default values for gold chart
# tags                : [ chart ]
# categories          : [ k8s, helm ]
# ------------------------------------------------------------------
# clear:^\s*##.*$

## @section Setings
## @descriptionStart
## no desctiption.
## @descriptionEnd
Setings:
  ## @param Setings.debug
  debug: false

## @section global
## @descriptionStart
## no desctiption.
## @descriptionEnd
global:
  ## @param global.some
  some: true



## @section Names
## @descriptionStart
## no desctiption.
## @descriptionEnd
Names:
  ## @extra Names.override [object]
  override:
    ## @param Names.override.name
    name     : ""
    ## @param Names.override.fullname
    fullname : ""
    ## @param Names.override.namespace
    namespace: ""

## @section Security
## @descriptionStart
## no desctiption.
## @descriptionEnd
Security:
  ## @param Security.include
  include: false


## @section Deployment
## @descriptionStart
## no desctiption.
## @descriptionEnd
Deployment:
  ## @param Deployment.test
  test    : false
  ## @param Deployment.replicas
  replicas: 1

  ## @section Deployment.Autoscaling - ``
  Autoscaling:
    ## @param Deployment.Autoscaling.enabled
    enabled                        : false
    ## @param Deployment.Autoscaling.minReplicas
    minReplicas                    : 1
    ## @param Deployment.Autoscaling.maxReplicas
    maxReplicas                    : 100
    ## @param Deployment.Autoscaling.targetCPUUtilizationPercentage
    targetCPUUtilizationPercentage : 80
    # targetMemoryUtilizationPercentage: 80
    

  ## @section Deployment.Image - ``
  Image:
    ## @param Deployment.Image.repository
    repository : nginx
    ## @param Deployment.Image.tag
    tag        : ""
    ## @param Deployment.Image.pullPolicy
    pullPolicy : IfNotPresent
    ## @extra Deployment.Image.pullSecrets [array]
    pullSecrets:
      ## @param Deployment.Image.pullSecrets[0].name
      - name: regcred
  

  ## @section Deployment.Pod - ``
  Pod:
    ## @extra Deployment.Pod.annotations [object]
    annotations    : 
      ## @param Deployment.Pod.annotations.i
      i: pod-annotation
    ## @extra Deployment.Pod.labels [object]
    labels         : 
      ## @param Deployment.Pod.labels.i
      i: pod-label
    ## @param Deployment.Pod.securityContext
    securityContext: {}
      # fsGroup       : 2000


  ## @section Deployment.Container - ``
  Container:
    ## @param Deployment.Container.securityContext
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000


  ## @section Deployment.Probes - ``
  Probes:

        
    ## @extra Deployment.Probes.readinessProbe [object]
    readinessProbe:
      ## @extra Deployment.Probes.readinessProbe.httpGet [object]
      httpGet:
        ## @param Deployment.Probes.readinessProbe.httpGet.path
        path: /
        ## @param Deployment.Probes.readinessProbe.httpGet.port
        port: http


  ## @section Deployment.Resources - ``
  Resources:
    ## @extra Deployment.Resources.limits [object]
    limits:
      ## @param Deployment.Resources.limits.cpu
      cpu: 100m
      ## @param Deployment.Resources.limits.memory
      memory: 128Mi
    ## @extra Deployment.Resources.requests [object]
    requests:
      ## @param Deployment.Resources.requests.cpu
      cpu: 100m
      ## @param Deployment.Resources.requests.memory
      memory: 128Mi


  ## @section Deployment.Scheduling - ``
  Scheduling:
    ## @param Deployment.Scheduling.nodeSelector
    nodeSelector : {}
    ## @param Deployment.Scheduling.affinity
    affinity     : {}
    ## @param Deployment.Scheduling.tolerations
    tolerations  : []


  ## @section Deployment.Storage - ``
  Storage:
    ## @param Deployment.Storage.mounts
    mounts: []
    # - name: foo
    #   mountPath: "/etc/foo"
    #   readOnly: true
    ## @param Deployment.Storage.volumes
    volumes: []
    # - name: foo
    #   secret:
    #     secretName: mysecret
    #     optional: false


## @section Network
## @descriptionStart
## no desctiption.
## @descriptionEnd
Network:
  ## @param Network.include
  include: true

  ## @section Network.Service - ``
  Service:
    ## @param Network.Service.type
    type : ClusterIP
    ## @param Network.Service.port
    port : 80


  ## @section Network.Ingress - ``
  Ingress:
    ## @param Network.Ingress.enabled
    enabled     : true
    ## @param Network.Ingress.className
    className   : ""
    ## @param Network.Ingress.annotations
    annotations : {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"


    ## @section Network.Ingress.Hosts - ``
    Hosts:
      ## @param Network.Ingress.Hosts[0].host
      - host: testy.loc
        ## @extra Network.Ingress.Hosts[0].paths [array]
        paths:
          ## @param Network.Ingress.Hosts[0].paths[0].path
          - path     : /
            ## @param Network.Ingress.Hosts[0].paths[0].pathType
            pathType : ImplementationSpecific

    ## @param Network.Ingress.tls
    tls: []
      # - secretName: chart-example-tls
      #   hosts     :
      #     - chart-example.local


## @section ServiceAccount
## @descriptionStart
## no desctiption.
## @descriptionEnd
ServiceAccount:
  ## @param ServiceAccount.include
  include     : false
  ## @param ServiceAccount.name
  name        : ""
  ## @param ServiceAccount.automount
  automount   : true
  ## @param ServiceAccount.annotations
  annotations : {}


## @section Configs
## @descriptionStart
## no desctiption.
## @descriptionEnd
Configs:
  ## @param Configs.include
  include: false
  ## @extra Configs.files [object]
  files  :

    ## @param Configs.files.default_conf
    default_conf : |-
      # inserted by --set-file

    ## @param Configs.files.index_html
    index_html   : |-
      # inserted by --set-file

    ## @param Configs.files.50x_html
    50x_html     : |-
      # inserted by --set-file


## @section Redis [object]
Redis:
  ## @skip Redis.enabled
  enabled: false


## @section Common [object]
Common:
  ## @skip Common.enabled
  enabled: false
