# ------------------------------------------------------------------
# yaml-language-server: $schema=schemas/values.schema.json
# generator           : https://jsonformatter.org/yaml-to-jsonschema
# title               : Default values for gold chart
# tags                : [ chart ]
# categories          : [ k8s, helm ]
# ------------------------------------------------------------------

####
#* Default values
###
## @section global

global:
  some: true


####
#* Names values
###
## @section names

names:
  override:
    ## @param names.override.name This is to override the chart name.
    name     : ""
    ## @param names.override.fullname This is to override the chart name.
    fullname : ""
    ## @param names.override.namespace This is to override the chart namespace.  
    namespace: ""


####
#* Default values for the deployment
###
## @section deployment

####
## @param replicaCount This will set the replicaset count 
#* More information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

####
#* This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
###
## @param image.repository [default: REPOSITORY_NAME/<image name>] Image name
## @param image.tag        Overrides the image tag whose default is the chart appVersion.
## @param image.pullPolicy Sets the pull policy for images.
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag       : ""

####
#* This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
###
## @param imagePullSecrets Specify docker-registry secret names as an array
imagePullSecrets: []

####
#* Container resource requests and limits
#* ref: http://kubernetes.io/docs/user-guide/compute-resources/
###
## @skip resources Optional description
## @disabled-param resources.limits  The resources limits for the Kubewatch container
## @disabled-param resources.requests  The requested resources for the Kubewatch container
resources:
  #* We usually recommend not to specify default resources and to leave this as a conscious
  #* choice for the user. This also increases chances charts run on environments with little
  #* resources, such as Minikube. If you do want to specify resources, uncomment the following
  #* lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits: {}
    # cpu: 200m
    # memory: 256Mi
  requests: {}
    # cpu: 200m
    # memory: 10Mi

####
#* This is to setup the liveness and readiness probes. 
#* More information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
###
## @param livenessProbe [object] livenessProbe
livenessProbe:
  httpGet:
    path: /
    port: http

## @param readinessProbe [object] readinessProbe
readinessProbe:
  httpGet:
    path: /
    port: http

## @param volumes [array] Additional volumes on the output Deployment definition.
volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

## @param volumeMounts [array] Additional volumeMounts on the output Deployment definition.
volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

## @param nodeSelector [object]
nodeSelector: {}

## @param tolerations [array]
tolerations: []

## @param affinity [object]
affinity: {}

####
#* This is for setting Kubernetes Annotations to a Pod.
#* For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
###
## @param podAnnotations
podAnnotations: {}

####
#* This is for setting Kubernetes Labels to a Pod.
#* For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
###
## @param podLabels
podLabels: {}

####
#* This is for setting up the pod security context
###
## @param podSecurityContext
podSecurityContext: {}
  # fsGroup: 2000

####
#* This is for setting up the containers security context
###
## @param securityContext
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

####
#* This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
#* Specifies whether a ServiceAccount should be created
###
## @section serviceAccount
## @param serviceAccount.create Enable the creation of a ServiceAccount for Kubewatch pods
## @param serviceAccount.automount Automatically mount a ServiceAccount's API credentials?
## @param serviceAccount.annotations Annotations to add to the service account
## @param serviceAccount.name Name of the created ServiceAccount
#* If not set and create is true, a name is generated using the fullname template
serviceAccount:
  create     : false
  automount  : true
  annotations: {}
  name       : ""

####
#* This is for setting up a service. 
#* More information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
###
## @section service
## @param service.type The Kubernetes type of the service
## @param service.port The port of the service
service:
  #* This sets the service type. 
  #* More information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  #* This sets the ports. 
  #* More information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

####
#* This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
###
## @section ingress
## @param ingress.enabled
## @param ingress.className
## @param ingress.annotations
## @param ingress.hosts [array]
## @param ingress.tls [array]
ingress:
  enabled    : false
  className  : ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
    # - host: chart-example.local
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
  tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local


####
#* This block is for setting up the ConfigMap
###
## @section ConfigMap
## @param cfmFiles [object] list of ConfigMap files included by `--set-file`
cfmFiles:
  default.conf: |
    # inserted by --set-file

  index.html: |
    # inserted by --set-file

  50x.html: |
    # inserted by --set-file

####
#* This block is for setting up the secrets
###
## @section secrets
## @param sec.enabled Enable the security module
sec:
  enabled: true

####
#* This block is for setting up the redis subchart
###
## @section subchart.redis
## @param redis.enabled Enable the redis subchart
redis:
  enabled: false
