# ------------------------------------------------------------------
# yaml-language-server: $schema=../../chart/values.schema.json
# title               : Dev env.
# tags                : [ chart ]
# categories          : [ k8s, helm ]
# ------------------------------------------------------------------

Config:
  autoupdate:
    enabled: false
    paused: true
  extend:
    default: default
    image: skip
    power: min
    region: skip

global:
  some: false
