# ------------------------------------------------------------------
# yaml-language-server: $schema=../../chart/values.schema.json
# title               : Image "dev" version values for gold chart
# tags                : [ chart ]
# categories          : [ k8s, helm ]
# ------------------------------------------------------------------

Deployment:
  Image:
    repository: "nginx"
    tag       : "1.29.0"
