{{- if not .Values.Settings.debug -}}
{{- if .Values.Security.include   -}}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-test      # &spc.name -> dpl volumes
spec:

  provider  : vault   # accepted provider options: akeyless or azure or vault or gcp
  parameters:         # provider-specific parameters
    vaultAddress      : "http://vault.vault:8200"
    vaultAuthMountPath: "test-cluster" # <-- vault.k8s auth path
    roleName          : "test-role"    # <-- vault.auth.role
    objects: |
      - objectName: "test-pass-object-01"
        secretPath: "test-kv2/data/test-secret"
        secretKey : "test-password"
  
  
  ### auto generate k8s secret
  secretObjects:
  - secretName: sec-spc-generated
    type: Opaque
    data:
    - objectName: test-pass-object-01 # object ref
      key       : test-password

{{- end -}}
{{- end -}}
