stages:
- validation
- build

include: 
- local: '/cicd/lab/**.yml'

build_1:
  stage: build
  image: ubuntu:20.04
  script:
    - printenv
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web'
      when: always
    - when: never

