# include:
#  - local: /cicd/lab/validation.yml


stages:
  - build
  - validation

build_1:
  stage: build
  image: ubuntu:20.04
  script:
    - printenv
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web'

validate_1:
  stage: validation
  image: oven/bun:slim
  script:
    - printenv
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # - if: $CI_COMMIT_TAG
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
