include:
 - local: cicd/lab/validation.yml
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web'

default:
  image: ubuntu:20.04
stages:
  - build

build:
  stage: build

  script:
    - printenv
