# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version : '3'
interval: 500ms
dotenv  : [.env]
env     :
  CWD   : '{{ .ROOT_DIR }}'

includes:
  clin:
    aliases : [c]
    taskfile: tools/clin.yaml 
  helm:
    aliases : [h]
    taskfile: tools/helm.yaml 
  git:
    aliases : [g]
    taskfile: tools/git.yaml 

tasks:
  default: task -a | grep '{{.CLI_ARGS}}' | awk '{ print $2 }' | sed 's/.$//' | sed 's/^/task /'
  watch:
    aliases: [w]
    dir    : '{{ .TASKFILE_DIR }}'
    silent : false
    watch  : true
    sources:
      # - '**/chart/files/**/*.*'
      - 'chart/templates/**/*.*'
      # - '**/chart/*.{yaml,json}'
    cmds:
    - echo "Watching for changes in {{ .TASKFILE_DIR }}..."
    - task: helm:template



