# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version : '3'
interval: 500ms
dotenv  : [.env]
includes:
  clin:
    aliases : [c]
    taskfile: tasks/clin.yaml 
  helm:
    aliases : [h]
    taskfile: tasks/helm.yaml 
  git:
    aliases : [g]
    taskfile: tasks/git.yaml 

tasks:
  default: task -a | grep '{{.CLI_ARGS}}' | awk '{ print $2 }' | sed 's/.$//' | sed 's/^/task /'
  
  watch:
    desc    : ''
    aliases : [w]
    silent  : false
    dir     : '{{ .TASKFILE_DIR }}'
    watch   : true
    sources :
      # - '**/chart/files/**/*.*'
      - 'chart/templates/**/*.*'
      # - '**/chart/*.{yaml,json}'
    cmds:
    - task: helm:template



