# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'
tasks:

  doc-values:
    desc    : ''
    aliases : [ v ]
    dir     : '{{ .ROOT_DIR }}'
    cmds    : 
    - clin helm doc values -v chart/fill.values.yaml -r chart/docs/auto/values.md -s chart/values.schema.json

  doc-libs:
    desc    : ''
    aliases : [ l ]
    dir     : '{{ .ROOT_DIR }}'
    cmds    : 
    - clin helm doc libs -l chart/templates/_  -r chart/docs/auto/libs.md

  doc-fill:
    desc    : ''
    aliases : [ f ]
    dir     : '{{ .ROOT_DIR }}'
    cmds    :
    - clin helm doc fill -v chart/values.yaml > chart/fill.values.yaml

  promo:*:*:
    desc    : ''
    dir     : '{{ .ROOT_DIR }}'
    vars:
      SOURCE_ENV: '{{ index .MATCH 0 }}'
      TARGET_ENV: '{{ index .MATCH 1 }}'
    cmds    :
    - echo "Promo from {{ .SOURCE_ENV }} to {{ .TARGET_ENV }}"
    - clin helm mgr --action promo --source-env {{ .SOURCE_ENV }} --target-env {{ .TARGET_ENV }}
  pause:
    desc    : ''
    dir     : '{{ .ROOT_DIR }}'
    cmds    :
    - clin helm mgr --action pause

  x:
    desc: ''
    cmds:
    - task: doc-fill
    - task: doc-libs
    - task: doc-values

