# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

tasks:


  pull:
    desc   : ''
    aliases: [ps]
    silent : true
    dir    : '{{.ROOT_DIR}}'
    cmds:
    - helm repo update
    - rm -rf chart/charts/*
    - helm dependency update chart
    - task: unzip-rm
    
  unzip-rm:
    desc    : ''
    prompt  : unzip subcharts ?
    internal: true
    dir     : '{{.ROOT_DIR}}/chart/charts'
    cmds:
    - cat *.tgz | tar -xvzf  - -i 
    - rm -rf     *.tgz

  template:
    desc   : 'template'
    aliases: [ t ]
    silent : true
    dir    : '{{.ROOT_DIR}}'
    vars:
      OUTPUT       : '{{.ROOT_DIR}}/logs/tpl.yaml'
      RELEASE_NAME : test-chart
      PATH_TO_CHART: chart
      FLAGS        : '--debug'
      FILES        : '' #'--set-file cfg.index\\.html=chart/files/index.html --set-file cfg.default\\.conf=fchart/iles/default.conf --set-file cfg.50x\\.html=chart/files/50x.html'
    cmds:
    - helm template {{ .RELEASE_NAME }} {{ .PATH_TO_CHART }} {{ .FLAGS }} {{ .FILES }} > {{ .OUTPUT }}
