# ------------------------------------------------------------------
# yaml-language-server: $schema=../../chart/values.schema.json
# title               : Resources "prod" values for gold chart
# tags                : [ chart ]
# categories          : [ k8s, helm ]
# ------------------------------------------------------------------

Deployment:

  replicas: 2

  Resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
