apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "_.names.fullname" . }}
  labels:
    {{- include "_.labels.common" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "_.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "_.labels.common" . | nindent 8 }}
  
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.network.service.port }}
              protocol: TCP

          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
