apiVersion: v1
kind: Service
metadata:
  name: {{ include "_.names.fullname" . }}
  labels:
    {{- include "_.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.Network.Service.type }}
  ports:
    - port: {{ .Values.Network.Service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {}
